print('Hello, World!')
print('Hello, World!2')
print('Hello, World!3')
print('Hello, World!4')
print('stop this non' + 'sense')
print('stop this non' + 'sense' + '!')
print('stop this non' + 'sense' + '!' + '!')
